# Test Requests
# Check / configure / set the variables (e.g., BACKEND_HOST, etc.) prior to using

GET {{BACKEND_HOST}}/api/email/auth-url
Content-Type: application/json

###
POST {{BACKEND_HOST}}/api/email/send
Content-Type: application/json

{
  "to": "replace_with_your_recipient@yourhost.com",
  "subject": "Test Email",
  "text": "This is a test email sent from the Node.js backend.",
  "tokens": {
    "access_token": "replace_with_your_access_token",
    "refresh_token": "replace_with_your_refresh_token",
    "scope": "https://www.googleapis.com/auth/gmail.send",
    "token_type": "Bearer",
    "expiry_date": 1721267748686
  }
}
